import { Inter, JetBrains_Mono } from 'next/font/google';
import 'react-datepicker/dist/react-datepicker.css';
import OsDetector from './components/OsDetector';
import Providers from './components/providers/Providers';
import I18nProvider from './components/providers/i18nProvider';
import './globals.css';

const inter = Inter({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const jetbrainsMono = JetBrains_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${inter.variable} ${jetbrainsMono.variable}`}
      >
        <OsDetector />
        <I18nProvider>
          <Providers>{children}</Providers>
        </I18nProvider>
      </body>
    </html>
  );
}
